### ISSUE TITLE
필터링 기능 구현

### ISSUE THREAD

**Issue by 5unk3n** [5unk3n/chart#6]
# TODO

- [ ] 특정 데이터 구역을 하이라이트 하는 방식으로 필터링 구현
- [ ] id값(지역이름)을 이용해 필터링 버튼 구현 (동일한 id를 가진 데이터 구역만 하이라이트)
- [ ] 특정 데이터 구역을 클릭 시에도 필터링
